#!/bin/bash

if [ "$chef_env" != "" ]; then
  echo "Must set 'chef_env'"
  exit 1
fi

#knife box list -E ajh2 | grep -P '(bono|sipp)-(3|4)' | grep "Found node" | grep -v "cacti" | cut -d\  -f 3,8 | sort | while read description ip ; do
knife box list -E $chef_env | grep "Found node" | grep -v "cacti" | cut -d\  -f 3,8 | sort | while read description ip ; do
  knife ssh -x ubuntu "role:cacti AND chef_environment:$chef_env" '
    description='$description'
    ip='$ip'
    echo Configuring $description $ip...
    host_id=$(sudo php -q /usr/share/cacti/cli/add_device.php --template=3 --community=clearwater --avail=snmp --description=$description --ip=$ip | tee -a /tmp/knife-ssh.cacti | grep Success | sed -e "s/\(^.*(\|).*$\)//g")
    graph_id=$(sudo php -q /usr/share/cacti/cli/add_graphs.php --graph-type=cg --graph-template-id=4 --host-id=$host_id | tee -a /tmp/knife-ssh.cacti | grep "Graph Added" | sed -e "s/\(^[^)]*(\|).*$\)//g")
    sudo php -q /usr/share/cacti/cli/add_tree.php --type=node --node-type=graph --tree-id=1 --graph-id=$graph_id >> /tmp/knife-ssh.cacti
    if echo $description | grep -q bono ; then
      graph_id=$(sudo php -q /usr/share/cacti/cli/add_graphs.php --graph-type=cg --graph-template-id=35 --host-id=$host_id | tee -a /tmp/knife-ssh.cacti | grep "Graph Added" | sed -e "s/\(^[^)]*(\|).*$\)//g")
      sudo php -q /usr/share/cacti/cli/add_tree.php --type=node --node-type=graph --tree-id=1 --graph-id=$graph_id >> /tmp/knife-ssh.cacti
      graph_id=$(sudo php -q /usr/share/cacti/cli/add_graphs.php --graph-type=cg --graph-template-id=37 --host-id=$host_id | tee -a /tmp/knife-ssh.cacti | grep "Graph Added" | sed -e "s/\(^[^)]*(\|).*$\)//g")
      sudo php -q /usr/share/cacti/cli/add_tree.php --type=node --node-type=graph --tree-id=1 --graph-id=$graph_id >> /tmp/knife-ssh.cacti
    fi
    if echo $description | grep -q sipp ; then
      graph_id=$(sudo php -q /usr/share/cacti/cli/add_graphs.php --graph-type=cg --graph-template-id=36 --host-id=$host_id | tee -a /tmp/knife-ssh.cacti | grep "Graph Added" | sed -e "s/\(^[^)]*(\|).*$\)//g")
      sudo php -q /usr/share/cacti/cli/add_tree.php --type=node --node-type=graph --tree-id=1 --graph-id=$graph_id >> /tmp/knife-ssh.cacti
    fi
    if echo $description | egrep -q sprout ; then
      graph_id=$(sudo php -q /usr/share/cacti/cli/add_graphs.php --graph-type=cg --graph-template-id=38 --host-id=$host_id | tee -a /tmp/knife-ssh.cacti | grep "Graph Added" | sed -e "s/\(^[^)]*(\|).*$\)//g")
      sudo php -q /usr/share/cacti/cli/add_tree.php --type=node --node-type=graph --tree-id=1 --graph-id=$graph_id >> /tmp/knife-ssh.cacti
    fi
    cat /tmp/knife-ssh.cacti
    rm /tmp/knife-ssh.cacti'
done
